name = "gym-tracker"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"

[vars]
NODE_ENV = "production"
VITE_SUPABASE_URL=https://wckofmynhlnqqoahebrb.supabase.co